version: "3.7"

services:
  web:
    image: crisisconnector/api:latest
    volumes:
      - ./api/services/web/:/usr/src/app/
    ports:
      - 81:5000
    environment:
      - "DB_URL=${DB_URL:-host.docker.internal:82}"
    depends_on:
      - ui
  ui:
    image: crisisconnector/ui:latest
    ports:
      - 80:80
    environment:
      - "API_URL=http://web:5000"
